//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class bas_Class
    {
        [Key]
        public int cla_ID { get; set; }
        public string cla_Name { get; set; }
        public Nullable<int> cla_SchoolID { get; set; }
        public string cla_SchoolName { get; set; }
        public Nullable<int> cla_TeacherID { get; set; }
        public string cla_TeacherName { get; set; }
        public Nullable<int> cla_StudentCount { get; set; }
        public string cla_FillCategoryName { get; set; }
        public string cla_FillCategoryIDs { get; set; }
        public string cla_RegionFullName { get; set; }
        public string cla_Note { get; set; }
        public Nullable<int> cla_Grade { get; set; }
        public Nullable<int> cla_OpenFunction { get; set; }
        public Nullable<int> cla_TeacherCount { get; set; }
    }
}
