//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class bas_School
    {
        [Key]
        public int sch_ID { get; set; }
        public string sch_Name { get; set; }
        public Nullable<int> sch_ProvinceID { get; set; }
        public Nullable<int> sch_CityID { get; set; }
        public Nullable<int> sch_CountyID { get; set; }
        public string sch_RegionFullName { get; set; }
        public string sch_Address { get; set; }
        public Nullable<int> sch_TeacherID { get; set; }
        public string sch_TeacherName { get; set; }
        public Nullable<System.DateTime> sch_CreateDate { get; set; }
        public Nullable<int> sch_AllowRegRealAccountCount { get; set; }
        public Nullable<int> sch_RegisteredRealCount { get; set; }
        public Nullable<int> sch_AllowRegTestAccountCount { get; set; }
        public Nullable<int> sch_RegisteredTestCount { get; set; }
        public string sch_Note { get; set; }
        public Nullable<int> sch_AllowRegRealAccountCount1 { get; set; }
        public Nullable<int> sch_RegisteredRealCount1 { get; set; }
        public Nullable<int> sch_AllowRegRealAccountCount2 { get; set; }
        public Nullable<int> sch_RegisteredRealCount2 { get; set; }
        public Nullable<int> sch_AllowRegRealAccountCount3 { get; set; }
        public Nullable<int> sch_RegisteredRealCount3 { get; set; }
        public Nullable<int> sch_OpenFunction { get; set; }
        public string sch_WXTel { get; set; }
        public Nullable<int> sch_CRMSchoolID { get; set; }
    }
}
