//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class bas_Student
    {
        [Key]
        public int s_ID { get; set; }
        public string s_Name { get; set; }
        public Nullable<int> s_Sex { get; set; }
        public Nullable<System.DateTime> s_Birthday { get; set; }
        public string s_Phone { get; set; }
        public string s_QQ { get; set; }
        public string s_WeiXin { get; set; }
        public string s_EMail { get; set; }
        public string s_ParentName { get; set; }
        public string s_ParentPhone { get; set; }
        public Nullable<int> s_ProvinceID { get; set; }
        public Nullable<int> s_CityID { get; set; }
        public Nullable<int> s_CountyID { get; set; }
        public string s_RegionFullName { get; set; }
        public Nullable<int> s_Integral { get; set; }
        public Nullable<int> s_Gold { get; set; }
        public string s_LoginID { get; set; }
        public string s_Password { get; set; }
        public Nullable<int> s_SchoolID { get; set; }
        public string s_SchoolName { get; set; }
        public Nullable<int> s_ClassID { get; set; }
        public string s_ClassName { get; set; }
        public Nullable<System.DateTime> s_ValidDate { get; set; }
        public Nullable<System.DateTime> s_CreateDate { get; set; }
        public Nullable<System.DateTime> s_LastLoginDate { get; set; }
        public string s_LastLoginIP { get; set; }
        public string s_LastLoginArea { get; set; }
        public string s_Referrer { get; set; }
        public Nullable<bool> s_IsEnabled { get; set; }
        public Nullable<int> s_AccountType { get; set; }
        public Nullable<System.DateTime> s_ActivationDate { get; set; }
        public string s_InitPassword { get; set; }
        public Nullable<int> s_RegTeacherID { get; set; }
        public string s_RegTeacherName { get; set; }
        public string s_Note { get; set; }
        public Nullable<System.DateTime> s_UpdateIntegralTime { get; set; }
        public Nullable<System.DateTime> s_CheckinDate { get; set; }
        public Nullable<int> s_Grade { get; set; }
        public Nullable<int> s_TimeCycle { get; set; }
        public Nullable<int> s_StudyConfig { get; set; }
    }
}
