//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sum_PKSummarize
    {
        [Key]
        public int sps_Student1ID { get; set; }
        public int sps_Student2ID { get; set; }
        public System.DateTime sps_CreateDate { get; set; }
        public string sps_Student1Name { get; set; }
        public string sps_Student2Name { get; set; }
        public Nullable<int> sps_Score1 { get; set; }
        public Nullable<int> sps_Score2 { get; set; }
        public Nullable<int> sps_Win { get; set; }
        public string sps_CategoryIDs { get; set; }
        public string sps_CategoryNames { get; set; }
        public Nullable<int> sps_Type { get; set; }
        public string sps_PKGuid { get; set; }
        public Nullable<int> sps_Gold { get; set; }
    }
}
