//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sum_ReciteTextSummarize
    {
        [Key]
        public int sts_StudentID { get; set; }
        public int sts_CategoryID1 { get; set; }
        public int sts_CategoryID2 { get; set; }
        public int sts_CategoryID3 { get; set; }
        public string sts_FillCategoryName { get; set; }
        public Nullable<System.DateTime> sts_CreateDate { get; set; }
        public Nullable<int> sts_FillScore { get; set; }
        public Nullable<int> sts_MaxScore { get; set; }
        public Nullable<int> sts_LastScore { get; set; }
        public Nullable<System.DateTime> sts_LastDate { get; set; }
        public Nullable<int> sts_RightCount { get; set; }
        public Nullable<int> sts_ErrorCount { get; set; }
        public Nullable<int> sts_LXCount { get; set; }
    }
}
