//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class sum_AssessmentDetail
    {
        [Key]
        [Column(Order = 1)]
        public int sad_StudentID { get; set; }
        [Key]
        [Column(Order = 2)]
        public Nullable<int> sad_CategoryID1 { get; set; }
        [Key]
        [Column(Order = 3)]
        public Nullable<int> sad_CategoryID2 { get; set; }
        [Key]
        [Column(Order = 4)]
        public Nullable<int> sad_TestID { get; set; }
        public System.DateTime sad_CreateDate { get; set; }
        public string sad_TestName { get; set; }
        public Nullable<decimal> sad_FillScore { get; set; }
        public Nullable<decimal> sad_Score { get; set; }
        public string sad_TestReport { get; set; }
        public string sad_GUID { get; set; }
        public string sad_TestIDs { get; set; }
    }
}
