//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sum_ReadSummarize
    {
        [Key]
        public int srs_StudentID { get; set; }
        public Nullable<int> srs_CategoryID1 { get; set; }
        public Nullable<int> srs_CategoryID2 { get; set; }
        public int srs_ReadID { get; set; }
        public string srs_ReadName { get; set; }
        public Nullable<System.DateTime> srs_CreateDate { get; set; }
        public Nullable<System.DateTime> srs_LastDate { get; set; }
        public Nullable<int> srs_WordCount { get; set; }
        public Nullable<int> srs_MaxSpeed { get; set; }
        public Nullable<int> srs_LastSpeed { get; set; }
    }
}
