//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sum_StructureDetail
    {
        [Key]
        public int ssd_StudentID { get; set; }
        public Nullable<int> ssd_CategoryID1 { get; set; }
        public Nullable<int> ssd_CategoryID2 { get; set; }
        public Nullable<int> ssd_TestID { get; set; }
        public System.DateTime ssd_CreateDate { get; set; }
        public string ssd_TestName { get; set; }
        public Nullable<decimal> ssd_FillScore { get; set; }
        public Nullable<decimal> ssd_Score { get; set; }
    }
}
