//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sum_StudySummarizeDay
    {
        [Key]
        public int s_ID { get; set; }
        public Nullable<int> msd_WStudyCount { get; set; }
        public Nullable<int> msd_WLearnCount { get; set; }
        public Nullable<int> msd_WNewCount { get; set; }
        public Nullable<int> msd_GStudyCount { get; set; }
        public Nullable<int> msd_GLearnCount { get; set; }
        public Nullable<int> msd_GNewCount { get; set; }
        public Nullable<int> msd_ReciteTextCount { get; set; }
        public Nullable<int> msd_PKCount { get; set; }
        public Nullable<int> msd_PKWinCount { get; set; }
        public Nullable<int> msd_PKFailCount { get; set; }
        public Nullable<int> msd_TestCount { get; set; }
        public Nullable<int> msd_ReadCount { get; set; }
        public Nullable<int> msd_ReadWordCount { get; set; }
        public Nullable<int> msd_CreateDate { get; set; }
    }
}
