//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sum_WordSummarize
    {
        [Key]
        public int sws_StudentID { get; set; }
        public int sws_CategoryID1 { get; set; }
        public int sws_CategoryID2 { get; set; }
        public int sws_CategoryID3 { get; set; }
        public string sws_FillCategoryName { get; set; }
        public Nullable<System.DateTime> sws_CreateDate { get; set; }
        public Nullable<int> sws_FillScore { get; set; }
        public Nullable<int> sws_MaxScore { get; set; }
        public Nullable<int> sws_LastScore { get; set; }
        public Nullable<System.DateTime> sws_LastDate { get; set; }
        public Nullable<int> sws_RightCount { get; set; }
        public Nullable<int> sws_ErrorCount { get; set; }
        public Nullable<int> sws_LearningSteps { get; set; }
        public Nullable<System.DateTime> sws_LearningDate { get; set; }
        public Nullable<int> sws_QSYXCount { get; set; }
        public Nullable<int> sws_ZNSJCount { get; set; }
        public Nullable<int> sws_ZNTXCount { get; set; }
        public Nullable<int> sws_ZNMXCount { get; set; }
        public Nullable<int> sws_XHCSCount { get; set; }
        public Nullable<int> sws_TestTime { get; set; }
    }
}
