//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sum_ReadDetail
    {
        [Key]
        public int srd_StudentID { get; set; }
        public Nullable<int> srd_CategoryID1 { get; set; }
        public Nullable<int> srd_CategoryID2 { get; set; }
        public int srd_ReadID { get; set; }
        public System.DateTime srd_CreateDate { get; set; }
        public string srd_ReadName { get; set; }
        public Nullable<int> srd_WordCount { get; set; }
        public Nullable<int> srd_Speed { get; set; }
    }
}
