//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sum_AssessmentSummarize
    {
        [Key]
        public int sas_StudentID { get; set; }
        public int sas_CategoryID1 { get; set; }
        public int sas_CategoryID2 { get; set; }
        public int sas_TestID { get; set; }
        public string sas_TestName { get; set; }
        public Nullable<System.DateTime> sas_CreateDate { get; set; }
        public Nullable<System.DateTime> sas_LastDate { get; set; }
        public Nullable<int> sas_FillScore { get; set; }
        public Nullable<decimal> sas_MaxScore { get; set; }
        public Nullable<decimal> sas_LastScore { get; set; }
        public Nullable<int> sas_TestCount { get; set; }
        public string sas_TestReport { get; set; }
    }
}
