//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sum_ReciteTextDetail
    {
        [Key]
        public int std_StudentID { get; set; }
        public int std_CategoryID1 { get; set; }
        public int std_CategoryID2 { get; set; }
        public int std_CategoryID3 { get; set; }
        public System.DateTime std_CreateDate { get; set; }
        public string std_FillCategoryName { get; set; }
        public Nullable<int> std_FillScore { get; set; }
        public Nullable<int> std_Score { get; set; }
        public Nullable<int> std_RightCount { get; set; }
        public Nullable<int> std_ErrorCount { get; set; }
    }
}
