//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sum_StructureSummarize
    {
        [Key]
        public int sss_StudentID { get; set; }
        public int sss_CategoryID1 { get; set; }
        public int sss_CategoryID2 { get; set; }
        public int sss_TestID { get; set; }
        public string sss_TestName { get; set; }
        public Nullable<System.DateTime> sss_CreateDate { get; set; }
        public Nullable<System.DateTime> sss_LastDate { get; set; }
        public Nullable<int> sss_FillScore { get; set; }
        public Nullable<decimal> sss_MaxScore { get; set; }
        public Nullable<decimal> sss_LastScore { get; set; }
        public Nullable<int> sss_StudyCount { get; set; }
        public Nullable<int> sss_TestCount { get; set; }
    }
}
