//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sys_FillBlanks
    {
        [Key]
        public int sfb_ID { get; set; }
        public int sp_ID { get; set; }
        public string sfb_Content { get; set; }
        public string sfb_Answer { get; set; }
        public int sfb_Number { get; set; }
        public decimal sfb_Score { get; set; }
        public int sfb_Index { get; set; }
        public string sfb_SoundPath { get; set; }
        public string sfb_Explain { get; set; }
        public Nullable<int> sfb_Num { get; set; }
        public string sfb_Knowledge { get; set; }
    }
}
