//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sys_TestPart
    {
        [Key]
        public int sp_ID { get; set; }
        public int st_ID { get; set; }
        public string sp_Name { get; set; }
        public int sp_PartType { get; set; }
        public Nullable<int> sp_Index { get; set; }
        public Nullable<int> sp_ItemCount { get; set; }
        public Nullable<decimal> sp_Score { get; set; }
        public string sp_Note { get; set; }
    }
}
