//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sys_Composition
    {
        [Key]
        public int scp_ID { get; set; }
        public int sp_ID { get; set; }
        public string scp_Content { get; set; }
        public Nullable<decimal> scp_Score { get; set; }
        public Nullable<int> scp_Index { get; set; }
        public string scp_explain { get; set; }
        public Nullable<int> scp_Num { get; set; }
    }
}
