//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sys_Test
    {
        [Key]
        public int st_ID { get; set; }
        public int sc_ID { get; set; }
        public string sc_Name { get; set; }
        public string st_ClassID { get; set; }
        public Nullable<int> st_ItemCount { get; set; }
        public Nullable<decimal> st_Score { get; set; }
        public string st_Note { get; set; }
        public Nullable<int> st_Index { get; set; }
        public Nullable<int> st_WordCount { get; set; }
        public Nullable<int> st_GlossaryCount { get; set; }
        public Nullable<int> st_Type { get; set; }
        public Nullable<bool> st_IsCheck { get; set; }
        public Nullable<int> st_Checker { get; set; }
        public Nullable<System.DateTime> st_CheckDate { get; set; }
    }
}
