//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sys_Dictionary
    {
        [Key]
        public string sd_Key { get; set; }
        public string sd_AudioWebUrl { get; set; }
        public string sd_pron { get; set; }
        public string sd_def { get; set; }
        public string sd_orig1 { get; set; }
        public string sd_trans1 { get; set; }
        public string sd_orig2 { get; set; }
        public string sd_trans2 { get; set; }
        public string sd_orig3 { get; set; }
        public string sd_trans3 { get; set; }
        public string sd_GQS { get; set; }
        public string sd_GQFC { get; set; }
        public string sd_XZFC { get; set; }
        public string sd_FS { get; set; }
        public Nullable<int> sd_IsGet { get; set; }
        public string sd_Split { get; set; }
        public string sd_PhotoUrl { get; set; }
    }
}
