//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sys_Select
    {
        [Key]
        public int ssl_ID { get; set; }
        public int sp_ID { get; set; }
        public string ssl_Content { get; set; }
        public string ssl_A { get; set; }
        public string ssl_B { get; set; }
        public string ssl_C { get; set; }
        public string ssl_D { get; set; }
        public string ssl_Result { get; set; }
        public Nullable<decimal> ssl_Score { get; set; }
        public Nullable<int> ssl_Index { get; set; }
        public string ssl_explain { get; set; }
        public Nullable<int> ssl_Num { get; set; }
        public string ssl_Knowledge { get; set; }
    }
}
