//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sys_Speaking
    {
        [Key]
        public int srt_CategoryID1 { get; set; }
        public int srt_CategoryID2 { get; set; }
        public int srt_CategoryID3 { get; set; }
        public string srt_Name { get; set; }
        public string srt_EnglishFilePath { get; set; }
        public string srt_ChineseFilePath { get; set; }
        public string srt_SountPath { get; set; }
        public Nullable<int> srt_LengthTime { get; set; }
        public Nullable<int> srt_WordCount { get; set; }
        public Nullable<int> srt_GlossaryCount { get; set; }
        public string srt_ImageFile { get; set; }
        public Nullable<int> srt_GrammarCount { get; set; }
    }
}
