//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sys_Error
    {
        [Key]
        public int ser_ID { get; set; }
        public int sp_ID { get; set; }
        public string ser_Content { get; set; }
        public string ser_Answer { get; set; }
        public int ser_Number { get; set; }
        public decimal ser_Score { get; set; }
        public int ser_Index { get; set; }
        public string ser_Explain { get; set; }
        public Nullable<int> ser_Num { get; set; }
    }
}
