//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sys_Item
    {
        [Key]
        public int si_ID { get; set; }
        public int sig_ID { get; set; }
        public string si_Content { get; set; }
        public string si_A { get; set; }
        public string si_B { get; set; }
        public string si_C { get; set; }
        public string si_D { get; set; }
        public string si_Result { get; set; }
        public decimal si_Score { get; set; }
        public int si_Index { get; set; }
        public string si_Explain { get; set; }
    }
}
