//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class wx_ActivityApply
    {
        [Key]
        public int waa_ActivityID { get; set; }
        public string waa_OpenId { get; set; }
        public string waa_Name { get; set; }
        public Nullable<int> waa_Sex { get; set; }
        public string waa_Mobile { get; set; }
        public string waa_School { get; set; }
        public Nullable<int> waa_Grade { get; set; }
        public string waa_class { get; set; }
        public Nullable<System.DateTime> waa_ApplyTime { get; set; }
        public Nullable<int> waa_SchoolId { get; set; }
        public Nullable<int> waa_SystemId { get; set; }
        public Nullable<int> waa_Status { get; set; }
        public string waa_Remark { get; set; }
        public Nullable<System.DateTime> waa_ReturnVisitDate { get; set; }
        public string waa_Operator { get; set; }
    }
}
