//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class wx_AssessmentDetailTemp
    {
        [Key]
        public string wad_OpenID { get; set; }
        public Nullable<int> wad_CategoryID1 { get; set; }
        public Nullable<int> wad_CategoryID2 { get; set; }
        public Nullable<int> wad_TestID { get; set; }
        public System.DateTime wad_CreateDate { get; set; }
        public string wad_TestName { get; set; }
        public Nullable<decimal> wad_FillScore { get; set; }
        public Nullable<decimal> wad_Score { get; set; }
        public string wad_TestReport { get; set; }
        public string wad_GUID { get; set; }
        public string wad_TestIDs { get; set; }
        public Nullable<int> wad_TestSpendTime { get; set; }
        public Nullable<int> wad_SystemId { get; set; }
        public string wad_TestReportPC { get; set; }
    }
}
