//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class wx_RegTrialAccount
    {
        [Key]
        public int wtr_Id { get; set; }
        public string wtr_OpenId { get; set; }
        public string wtr_Name { get; set; }
        public string wtr_Mobile { get; set; }
        public string wtr_Password { get; set; }
        public Nullable<int> wtr_grade { get; set; }
        public Nullable<System.DateTime> wtr_CreateTime { get; set; }
        public Nullable<System.DateTime> wtr_UpdateTime { get; set; }
        public Nullable<int> wtr_FromSystem { get; set; }
        public Nullable<int> wtr_Status { get; set; }
        public Nullable<int> wtr_SuccessSytems { get; set; }
        public Nullable<int> wtr_FailSytems { get; set; }
    }
}
