//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class wx_UserInfo
    {
        [Key]
        public string wxi_OpenId { get; set; }
        public string wxi_Name { get; set; }
        public string wxi_Telephone { get; set; }
        public Nullable<int> wxi_SchoolId { get; set; }
        public Nullable<System.DateTime> wxi_SubscribeDate { get; set; }
        public Nullable<System.DateTime> wxi_UnSubscribeDate { get; set; }
        public Nullable<int> wxi_Status { get; set; }
        public Nullable<System.DateTime> wxi_UpdateDate { get; set; }
        public string wxi_Ip { get; set; }
        public string wxi_Area { get; set; }
        public Nullable<System.DateTime> wxi_ContactInfoUpdateDate { get; set; }
        public Nullable<int> wxi_SystemId { get; set; }
    }
}
